name       : haskell-cmark
version    : '0.6'
release    : 3
source     :
    - https://hackage.haskell.org/package/cmark-0.6/cmark-0.6.tar.gz : 0dec55cd4e02ac6ff557044a9aa2523479afc88370d3838430b3e386bef981dc
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides Haskell bindings for libcmark, the reference parser for CommonMark, a fully specified variant of Markdown.
description: |
    This package provides Haskell bindings for libcmark, the reference parser for CommonMark, a fully specified variant of Markdown.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
