name       : haskell-cmark
version    : 0.5.6
release    : 2
source     :
    - https://hackage.haskell.org/package/cmark-0.5.6/cmark-0.5.6.tar.gz : 855c4b7aca6d4e9eb076beb6cc6f74e7578fae7aa3625fd3fca5e3b4901a32b0
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides Haskell bindings for libcmark, the reference parser for CommonMark, a fully specified variant of Markdown.
description: |
    This package provides Haskell bindings for libcmark, the reference parser for CommonMark, a fully specified variant of Markdown.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
